console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

# catppucin-macchiato
[palette]
  os = '#ACB0BE'
  closer = 'p:os'
  pink = '#F5BDE6'
  lavender = '#B7BDF8'
  overlay2 = '#939ab7'
  surface2 = '#5b6078'
  # yellow = '#939ab7'
  blue = '#8AADF4'
  sapphire = '#7dc4e4'

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent' 
    foreground = 'p:surface2' 
    template = '╭─' 

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:pink'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = "full"

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    background = 'transparent'
    foreground = 'p:lavender'
    # template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}'
    # template = "{{ .HEAD }}<p:sapphire>{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} </>"
    [blocks.segments.properties]
        branch_icon = ''
        commit_icon = '@'
        fetch_status = true

[[blocks]]
  type = 'prompt'
  overflow = 'hidden'
  alignment = 'right'
  filler = "{{ if .Overflow }} {{ else }}<p:surface2>·</>{{ end }}"

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = ' {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000 

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'p:overlay2'
    background = 'transparent'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  
  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent' 
    foreground = 'p:surface2' 
    template = '╰─'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    background = 'transparent' 
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}p:closer{{end}}", 
    ]
    template = '❯'

[transient_prompt]
  background = 'transparent'
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}p:closer{{end}}", 
  ]
  template = '❯ '

[secondary_prompt]
  foreground = 'p:closer' 
  background = 'transparent'
  template = '❯❯ '
