splash = false

wallpaper {
    monitor = 
    path = ~/Pictures/Wallpapers/mountain-07.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-8
    path = ~/Pictures/Wallpapers/mountain-07.jpg
    fit_mode = cover
}

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/mountain-07.jpg
    fit_mode = cover
}
